package edu.val.dto.oracle;
// Generated 24-jun-2017 14:13:37 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Registroautoid generated by hbm2java
 */
@Entity
@Table(name = "REGISTROID", schema = "HR")
@SequenceGenerator(name="sequito", sequenceName = "REGISTROID_SEQ2", allocationSize=1, initialValue=0)
public class Registroid implements java.io.Serializable {

	private Integer id;

	public Registroid() {
	}

	public Registroid(Integer id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequito")
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

}
