package edu.val.dto.oracle;
// Generated 24-jun-2017 12:37:16 by Hibernate Tools 4.3.1.Final

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

/**
 * Registro generated by hbm2java
 */
@Entity
@Table(name = "REGISTROTABLA", schema = "HR")
@TableGenerator(
	    name="course",
	    table="HIBERNATE_SEQUENCE",
	    pkColumnName="sequence_name",
	    valueColumnName = "nextval",
	    allocationSize=30
	)
public class Registrotabla implements java.io.Serializable {

	private Integer id;

	public Registrotabla() {
	}

	public Registrotabla(Integer id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="course")
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

}
